- name: "install go"
  unarchive: src={{ tarballs_dir }}/{{ go_tarball }} dest=/usr/local creates=/usr/local/go
  become: yes
- name: "add go to PATH in bash_profile"
  lineinfile: dest=/home/{{ cluster_user }}/.bash_profile insertafter="^PATH=" line="PATH=$PATH:/usr/local/go/bin"

